id: 68ff2a5994334aa2a9bec58be0b9340e
initial_creation_type: ocr
source_metadata:
  volumes:
    8c55ff51a14149af84cd8e224320cc40:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ཕུང་པོ་ལྔའི་བཤད་པ།
      total_pages: 1517
      volume_number: 77
